import React, { useMemo, useState } from 'react';
import { useLocation } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext';
import { Card } from '../ui/Card';
import { Button } from '../ui/Button';
import { Bell, Bookmark, Calendar, CheckCircle2, Clock, Flag, Lock, Search, ShieldCheck, Sparkles, Target, TrendingUp, Users, X } from 'lucide-react';

const storageKey = (id: number | string | undefined, name: string) => `skillbarter_feature_${id || 'guest'}_${name}`;
const read = <T,>(key: string, fallback: T): T => { try { const v = localStorage.getItem(key); return v ? JSON.parse(v) : fallback; } catch { return fallback; } };

export const PlatformEnhancements: React.FC = () => {
  const { currentUser } = useAuth();
  const { pathname } = useLocation();
  const id = currentUser?.id;
  const offered = currentUser?.skills?.filter((s: any) => s.skill_type === 'OFFERED').map((s: any) => s.skill_name) || [];
  const needed = currentUser?.skills?.filter((s: any) => s.skill_type === 'NEEDED').map((s: any) => s.skill_name) || [];
  const trust = Math.round(currentUser?.trust_score || 94);
  const [bookmarks, setBookmarks] = useState<string[]>(() => read(storageKey(id, 'bookmarks'), []));
  const [bookmarkInput, setBookmarkInput] = useState('');
  const [availability, setAvailability] = useState<any>(() => read(storageKey(id, 'availability'), { days: ['Mon', 'Wed', 'Fri'], from: '18:00', to: '21:00' }));
  const [status, setStatus] = useState(() => read(storageKey(id, 'exchange'), 'Requested'));
  const [notifications, setNotifications] = useState<any>(() => read(storageKey(id, 'notifications'), { requests: true, exchanges: true, messages: true, recommendations: true }));
  const [quietHours, setQuietHours] = useState(() => read(storageKey(id, 'quietHours'), false));
  const [savedSearch, setSavedSearch] = useState(() => read(storageKey(id, 'savedSearch'), false));
  const [goals, setGoals] = useState<any>(() => read(storageKey(id, 'goals'), { weekly: 3, completed: 1 }));
  const [verification, setVerification] = useState<any>(() => read(storageKey(id, 'verification'), { email: true, phone: false, identity: false }));
  const [privacy, setPrivacy] = useState<any>(() => read(storageKey(id, 'privacy'), { profile: true, availability: true, activity: false }));
  const [report, setReport] = useState('');
  const [reportSent, setReportSent] = useState(false);
  const save = (name: string, value: unknown) => localStorage.setItem(storageKey(id, name), JSON.stringify(value));
  const addBookmark = () => { const v = bookmarkInput.trim(); if (!v) return; const next = Array.from(new Set([...bookmarks, v])); setBookmarks(next); save('bookmarks', next); setBookmarkInput(''); };
  const trustParts = useMemo(() => [['Exchanges', .30], ['Ratings', .25], ['Verification', .25], ['Activity', .20]] as const, []);

  if (pathname === '/feed') return <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 -mt-2 pb-6"><div className="grid grid-cols-1 md:grid-cols-4 gap-3">
    <Card className="p-4"><div className="flex items-center gap-2 mb-2"><Sparkles className="w-4 h-4 text-emerald-600"/><h3 className="text-xs font-bold">Smart Recommendations</h3></div><p className="text-[11px] text-slate-500 mb-2">Matches based on your learning goals.</p><div className="flex flex-wrap gap-1">{(needed.slice(0, 3).length ? needed.slice(0, 3) : ['Web Development', 'Photography']).map((s: string) => <span key={s} className="px-2 py-1 rounded-lg bg-emerald-50 text-emerald-800 text-[10px] font-semibold">{s}</span>)}</div></Card>
    <Card className="p-4"><div className="flex items-center gap-2 mb-2"><ShieldCheck className="w-4 h-4 text-emerald-600"/><h3 className="text-xs font-bold">Trust Overview</h3></div><div className="flex items-end gap-2"><span className="text-2xl font-black text-emerald-700">{trust}</span><span className="text-[10px] text-slate-400 mb-1">/ 100</span></div><div className="mt-2 h-1.5 bg-slate-100 rounded-full"><div className="h-full bg-emerald-500 rounded-full" style={{ width: `${trust}%` }}/></div></Card>
    <Card className="p-4"><div className="flex items-center gap-2 mb-2"><Bookmark className="w-4 h-4 text-emerald-600"/><h3 className="text-xs font-bold">Quick Bookmarks</h3></div><div className="flex gap-1.5"><input value={bookmarkInput} onChange={e => setBookmarkInput(e.target.value)} onKeyDown={e => e.key === 'Enter' && addBookmark()} placeholder="Save a skill" className="min-w-0 flex-1 px-2.5 py-1.5 rounded-lg border border-slate-200 text-[10px]"/><Button size="sm" onClick={addBookmark}>Save</Button></div><div className="flex flex-wrap gap-1 mt-2">{bookmarks.slice(0, 4).map(s => <span key={s} className="px-2 py-1 rounded-lg bg-slate-100 text-[10px]">{s}</span>)}</div></Card>
    <Card className="p-4"><div className="flex items-center gap-2 mb-2"><TrendingUp className="w-4 h-4 text-emerald-600"/><h3 className="text-xs font-bold">Weekly Goal</h3></div><div className="text-xl font-black">{goals.completed}/{goals.weekly}</div><div className="h-1.5 bg-slate-100 rounded-full mt-2"><div className="h-full bg-emerald-500 rounded-full" style={{width:`${Math.min(100, goals.completed/goals.weekly*100)}%`}}/></div><Button size="sm" className="mt-2" onClick={() => { const n={...goals,completed:Math.min(goals.weekly,goals.completed+1)}; setGoals(n); save('goals',n); }}>Log progress</Button></Card>
  </div></div>;

  if (pathname.startsWith('/discover')) return <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 -mt-2 pb-6"><Card className="p-4"><div className="flex flex-col lg:flex-row lg:items-center justify-between gap-3"><div><div className="flex items-center gap-2"><Search className="w-4 h-4 text-emerald-600"/><h3 className="text-xs font-bold">Advanced Discovery</h3></div><p className="text-[10px] text-slate-500 mt-1">Refine the existing search with level, distance and skill preferences.</p></div><div className="flex flex-wrap gap-2"><select className="px-2.5 py-1.5 rounded-lg border border-slate-200 text-[10px]"><option>Any Level</option><option>Beginner</option><option>Intermediate</option><option>Advanced</option></select><select className="px-2.5 py-1.5 rounded-lg border border-slate-200 text-[10px]"><option>Within 5 km</option><option>Within 10 km</option><option>Within 25 km</option><option>Within 50 km</option></select><span className="px-2.5 py-1.5 rounded-lg bg-emerald-50 text-emerald-700 text-[10px] font-semibold">{offered.length} skills offered</span><Button size="sm" variant="outline" onClick={() => {setSavedSearch(!savedSearch); save('savedSearch',!savedSearch);}}>{savedSearch ? 'Search Saved' : 'Save Search'}</Button></div></div></Card></div>;

  if (pathname.startsWith('/profile/')) return <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 -mt-2 pb-6"><div className="grid grid-cols-1 md:grid-cols-3 gap-3"><Card className="p-4 md:col-span-2"><div className="flex items-center gap-2 mb-2"><Clock className="w-4 h-4 text-emerald-600"/><h3 className="text-xs font-bold">Availability</h3></div><div className="flex flex-wrap gap-1 mb-2">{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(day => <button key={day} onClick={() => setAvailability((a:any) => ({...a,days:a.days.includes(day)?a.days.filter((d:string)=>d!==day):[...a.days,day]}))} className={`px-2 py-1 rounded-md text-[9px] font-bold ${availability.days.includes(day)?'bg-emerald-600 text-white':'bg-slate-100 text-slate-500'}`}>{day}</button>)}</div><div className="grid grid-cols-2 gap-2"><input type="time" value={availability.from} onChange={e=>setAvailability({...availability,from:e.target.value})} className="p-1.5 rounded-lg border border-slate-200 text-[10px]"/><input type="time" value={availability.to} onChange={e=>setAvailability({...availability,to:e.target.value})} className="p-1.5 rounded-lg border border-slate-200 text-[10px]"/></div><Button size="sm" className="mt-2" onClick={()=>save('availability',availability)}>Save availability</Button></Card><Card className="p-4"><div className="flex items-center gap-2 mb-2"><ShieldCheck className="w-4 h-4 text-emerald-600"/><h3 className="text-xs font-bold">Trust Breakdown</h3></div>{trustParts.map(([label,weight])=><div key={label} className="mb-2"><div className="flex justify-between text-[9px]"><span>{label}</span><b>{Math.round(trust*weight)}/100</b></div><div className="h-1 bg-slate-100 rounded-full"><div className="h-full bg-emerald-500 rounded-full" style={{width:`${trust*weight}%`}}/></div></div>)}</Card></div></div>;

  if (pathname.startsWith('/learning')) return <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 -mt-2 pb-6"><Card className="p-4"><div className="flex items-center gap-2 mb-3"><Target className="w-4 h-4 text-emerald-600"/><h3 className="text-xs font-bold">Learning Goals Progress</h3><span className="ml-auto text-[10px] text-slate-500">{needed.length} active skill goals</span></div><div className="grid grid-cols-1 sm:grid-cols-3 gap-2">{(needed.length?needed:['Learn a new skill']).slice(0,3).map((skill:string,i:number)=><div key={skill} className="p-3 rounded-xl bg-slate-50"><div className="flex justify-between text-[10px] font-semibold"><span>{skill}</span><span>{[35,60,80][i]}%</span></div><div className="h-1.5 bg-white rounded-full mt-2"><div className="h-full bg-emerald-500 rounded-full" style={{width:`${[35,60,80][i]}%`}}/></div></div>)}</div></Card></div>;

  if (pathname.startsWith('/exchanges')) { const stages=['Requested','Accepted','Scheduled','In Progress','Completed']; return <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 -mt-2 pb-6"><Card className="p-4"><div className="flex items-center gap-2 mb-3"><Calendar className="w-4 h-4 text-emerald-600"/><h3 className="text-xs font-bold">Exchange Progress</h3><span className="ml-auto text-[10px] font-semibold text-emerald-700">{status}</span></div><div className="grid grid-cols-2 sm:grid-cols-5 gap-1">{stages.map(stage=><button key={stage} onClick={()=>{setStatus(stage);save('exchange',stage)}} className={`p-2 rounded-lg text-[9px] font-bold ${status===stage?'bg-emerald-600 text-white':'bg-slate-100 text-slate-500'}`}>{stage}</button>)}</div><div className="mt-2 h-1.5 bg-slate-100 rounded-full"><div className="h-full bg-emerald-500 rounded-full" style={{width:`${(stages.indexOf(status)+1)*20}%`}}/></div></Card></div>; }

  if (pathname.startsWith('/notifications')) return <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 -mt-2 pb-6"><Card className="p-4"><div className="flex items-center gap-2 mb-2"><Bell className="w-4 h-4 text-emerald-600"/><h3 className="text-xs font-bold">Smart Notification Preferences</h3></div><div className="grid grid-cols-2 sm:grid-cols-4 gap-2">{Object.entries(notifications).map(([name,value])=><label key={name} className="flex items-center justify-between gap-2 p-2 rounded-lg bg-slate-50 text-[10px] capitalize"><span>{name}</span><input type="checkbox" checked={Boolean(value)} onChange={e=>setNotifications((n:any)=>({...n,[name]:e.target.checked}))}/></label>)}</div><label className="flex items-center gap-2 mt-3 text-[10px]"><input type="checkbox" checked={quietHours} onChange={e=>{setQuietHours(e.target.checked);save('quietHours',e.target.checked)}}/> Quiet hours (10 PM–7 AM)</label><Button size="sm" className="mt-2" onClick={()=>save('notifications',notifications)}>Save preferences</Button></Card></div>;

  if (pathname.startsWith('/trust')) return <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 -mt-2 pb-6"><Card className="p-4"><div className="flex items-center gap-2 mb-3"><ShieldCheck className="w-4 h-4 text-emerald-600"/><h3 className="text-xs font-bold">Verification Readiness</h3><span className="ml-auto text-[10px] font-semibold text-emerald-700">{Object.values(verification).filter(Boolean).length}/3 complete</span></div><div className="grid grid-cols-1 sm:grid-cols-3 gap-2">{Object.entries(verification).map(([name,value])=><button key={name} onClick={()=>{const n={...verification,[name]:!value};setVerification(n);save('verification',n)}} className={`p-3 rounded-xl text-left text-[10px] ${value?'bg-emerald-50 border border-emerald-200':'bg-slate-50'}`}><CheckCircle2 className={`w-4 h-4 mb-1 ${value?'text-emerald-600':'text-slate-300'}`}/><b className="capitalize">{name} verification</b><p className="text-slate-500 mt-1">{value?'Completed':'Mark when completed'}</p></button>)}</div></Card></div>;

  if (pathname.startsWith('/settings')) return <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 -mt-2 pb-6"><Card className="p-4"><div className="flex items-center gap-2 mb-3"><Lock className="w-4 h-4 text-emerald-600"/><h3 className="text-xs font-bold">Privacy Controls</h3></div><div className="grid grid-cols-1 sm:grid-cols-3 gap-2">{Object.entries(privacy).map(([name,value])=><label key={name} className="flex items-center justify-between p-3 rounded-xl bg-slate-50 text-[10px] capitalize"><span>{name} visibility</span><input type="checkbox" checked={Boolean(value)} onChange={e=>{const n={...privacy,[name]:e.target.checked};setPrivacy(n);save('privacy',n)}}/></label>)}</div></Card></div>;

  if (pathname.startsWith('/community') || pathname.startsWith('/messages')) return <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 -mt-2 pb-6"><Card className="p-3"><div className="flex flex-col sm:flex-row sm:items-center gap-2 text-[10px] text-slate-500"><div className="flex items-center gap-2"><Flag className="w-4 h-4 text-amber-500"/><span>Community safety: report inappropriate users or content.</span></div><input value={report} onChange={e=>setReport(e.target.value)} placeholder="Brief reason" className="sm:ml-auto w-full sm:w-40 px-2 py-1.5 rounded-md border border-slate-200 text-[9px]"/>{reportSent?<CheckCircle2 className="w-4 h-4 text-emerald-600"/>:<Button size="sm" variant="outline" onClick={()=>{if(report.trim()){setReportSent(true);setReport('')}}}>Report</Button>}</div></Card></div>;

  return null;
};
