import React, { useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowLeft, ArrowRight, Bell, Calendar, CheckCircle2, Clock, HelpCircle, Lock, Search, Settings, ShieldCheck, Sparkles, Users, Wrench, BookOpen, CreditCard, Star, MessageCircle, Filter, Plus, Send, Heart, SlidersHorizontal, ChevronRight, Check, UserPlus, Award, Flag, Globe2, Zap } from 'lucide-react';

type ScreenEntry = readonly [string, string, string, React.ElementType];

const screens: ScreenEntry[] = [
  ['dashboard','Home Dashboard','Overview of exchanges, matches, requests and activity', Sparkles],
  ['edit-profile','Edit Profile','Update your bio, skills, availability and preferences', Settings],
  ['public-profile','Public Profile','Preview how other learners see your profile', Users],
  ['skills','Skills Management','Manage skills you teach and want to learn', Wrench],
  ['add-skill','Add New Skill','Add a skill with level, category and description', Sparkles],
  ['learning-goals','My Learning Goals','Track your current learning objectives', BookOpen],
  ['teaching-skills','My Teaching Skills','Organize the skills you can teach', Users],
  ['search','Skill Search','Find people by skill, level and availability', Search],
  ['advanced-search','Advanced Search & Filters','Refine discovery with detailed filters', Filter],
  ['recommended','Recommended Users','See suggested skill exchange partners', Users],
  ['ai-matching','AI Skill Matching','Discover matches based on your goals', Sparkles],
  ['match-details','Match Details','Review compatibility and shared goals', CheckCircle2],
  ['send-request','Send Skill Request','Create a focused skill exchange request', MessageCircle],
  ['incoming-requests','Incoming Requests','Review requests received from members', Bell],
  ['sent-requests','Sent Requests','Track requests you have sent', Clock],
  ['request-details','Request Details','View status, skills and next steps', CheckCircle2],
  ['active-exchange','Active Skill Exchange','Manage an exchange in progress', Wrench],
  ['exchange-history','Exchange History','Review completed and past exchanges', Clock],
  ['exchange-rating','Exchange Rating','Rate a completed learning exchange', Star],
  ['schedule','Schedule Exchange','Plan an exchange session', Calendar],
  ['calendar','Calendar','View upcoming exchange sessions and events', Calendar],
  ['notifications','Notifications','See requests, messages and updates', Bell],
  ['notification-settings','Notification Settings','Choose which activity alerts you receive', Bell],
  ['chat-details','Chat Details','Manage a conversation and exchange context', MessageCircle],
  ['create-post','Create Community Post','Share a question, tip or learning update', MessageCircle],
  ['post-details','Post Details','Read a community discussion and replies', MessageCircle],
  ['groups','Community Groups','Explore learning communities and topics', Users],
  ['group-details','Group Details','View group members, posts and activities', Users],
  ['workshops','Workshops','Discover workshops hosted by members', BookOpen],
  ['create-workshop','Create Workshop','Draft a workshop with schedule and capacity', BookOpen],
  ['workshop-details','Workshop Details','View workshop information and participation', BookOpen],
  ['my-workshops','My Workshops','Manage workshops you host or joined', BookOpen],
  ['credits','Skill Credits','View credit balance and credit activity', CreditCard],
  ['premium','Premium Membership','Explore premium benefits and status', CreditCard],
  ['verification','Verification Center','Manage verification requests', ShieldCheck],
  ['support','Help & Support','Get help with account and platform workflows', HelpCircle],
  ['faq','FAQ','Find answers to common SkillBarter questions', HelpCircle],
  ['privacy','Privacy & Security','Review privacy controls and security', Lock],
  ['account-settings','Account Settings','Manage account preferences', Settings],
  ['activity','Activity History','Review recent actions across your account', Clock],
];

const people: [string, string, string][] = [['Priya Sharma','Python ↔ UI/UX','96% match'],['Arjun Rao','React ↔ Data Science','91% match'],['Meera Nair','English ↔ JavaScript','88% match']];

const Button = ({ children, onClick, secondary = false }: { children: React.ReactNode; onClick?: () => void; secondary?: boolean }) => <button onClick={onClick} type="button" className={secondary ? 'rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50' : 'rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-indigo-700'}>{children}</button>;
const Card = ({ children, className = '' }: { children: React.ReactNode; className?: string }) => <div className={`rounded-2xl border border-slate-200 bg-white p-5 shadow-sm ${className}`}>{children}</div>;

function Dashboard() { return <><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['Active Exchanges','3','Keep learning'],['New Matches','12','This week'],['Pending Requests','4','Need attention'],['Skill Credits','180','Available']].map(([a,b,c]) => <Card key={a}><p className="text-sm text-slate-500">{a}</p><p className="mt-2 text-3xl font-bold">{b}</p><p className="mt-1 text-xs text-slate-400">{c}</p></Card>)}</div><div className="mt-6 grid gap-5 lg:grid-cols-3"><Card className="lg:col-span-2"><h2 className="font-bold">Today’s learning plan</h2><div className="mt-4 space-y-3">{['React hooks practice','Python mentoring with Priya','Complete exchange feedback'].map((x,i)=><div className="flex items-center justify-between rounded-xl bg-slate-50 p-4" key={x}><div><p className="font-medium">{x}</p><p className="text-xs text-slate-500">{i === 0 ? '30 min' : i === 1 ? '6:00 PM' : 'Due today'}</p></div><CheckCircle2 size={20} className="text-emerald-500"/></div>)}</div></Card><Card><h2 className="font-bold">Quick actions</h2><div className="mt-4 grid gap-2"><Link to="/discover" className="rounded-xl bg-indigo-50 p-3 text-sm font-semibold text-indigo-700">Find a partner</Link><Link to="/exchanges" className="rounded-xl bg-slate-50 p-3 text-sm font-semibold">Open exchanges</Link><Link to="/messages" className="rounded-xl bg-slate-50 p-3 text-sm font-semibold">View messages</Link></div></Card></div></>; }
function EditProfile() { const [saved,setSaved]=useState(false); return <Card><h2 className="text-xl font-bold">Profile information</h2><div className="mt-5 grid gap-4 md:grid-cols-2"><label className="text-sm font-medium">Display name<input className="mt-2 w-full rounded-xl border p-3" defaultValue="SkillBarter Member" /></label><label className="text-sm font-medium">Location<input className="mt-2 w-full rounded-xl border p-3" defaultValue="India" /></label><label className="text-sm font-medium md:col-span-2">Bio<textarea className="mt-2 min-h-28 w-full rounded-xl border p-3" defaultValue="I enjoy learning by exchanging practical skills with other people." /></label><label className="text-sm font-medium">Availability<select className="mt-2 w-full rounded-xl border p-3"><option>Weekday evenings</option><option>Weekends</option><option>Flexible</option></select></label><label className="text-sm font-medium">Learning mode<select className="mt-2 w-full rounded-xl border p-3"><option>Online</option><option>In person</option><option>Both</option></select></label></div><div className="mt-5 flex items-center gap-3"><Button onClick={()=>setSaved(true)}>{saved?'Saved ✓':'Save profile'}</Button>{saved&&<span className="text-sm text-emerald-600">Your changes are saved for this session.</span>}</div></Card>; }
function PublicProfile() { return <Card><div className="flex flex-col gap-5 sm:flex-row sm:items-center"><div className="flex h-20 w-20 items-center justify-center rounded-3xl bg-indigo-100 text-2xl font-bold text-indigo-700">SM</div><div><h2 className="text-2xl font-bold">SkillBarter Member</h2><p className="text-slate-500">Full-stack learner • Available evenings</p><div className="mt-2 flex gap-2"><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-semibold text-emerald-700">Verified</span><span className="rounded-full bg-slate-100 px-3 py-1 text-xs">4.9 ★</span></div></div></div><div className="mt-7 grid gap-4 md:grid-cols-2"><div><h3 className="font-semibold">Can teach</h3><div className="mt-2 flex flex-wrap gap-2">{['React','Python','Git','REST APIs'].map(x=><span key={x} className="rounded-lg bg-indigo-50 px-3 py-2 text-sm text-indigo-700">{x}</span>)}</div></div><div><h3 className="font-semibold">Wants to learn</h3><div className="mt-2 flex flex-wrap gap-2">{['UI/UX','Machine Learning','Public Speaking'].map(x=><span key={x} className="rounded-lg bg-slate-100 px-3 py-2 text-sm">{x}</span>)}</div></div></div><div className="mt-6 flex gap-3"><Button><UserPlus size={16} className="mr-2 inline"/>Connect</Button><Button secondary><MessageCircle size={16} className="mr-2 inline"/>Message</Button></div></Card>; }
function Skills() { const [skills,setSkills]=useState(['React','Python','Git','Natural Language Processing']); const [value,setValue]=useState(''); return <Card><div className="flex items-center justify-between"><div><h2 className="text-xl font-bold">Your skills</h2><p className="text-sm text-slate-500">Separate teaching skills from learning goals.</p></div><span className="rounded-full bg-indigo-50 px-3 py-1 text-xs font-bold text-indigo-700">{skills.length} skills</span></div><div className="mt-5 flex flex-wrap gap-2">{skills.map(s=><button type="button" onClick={()=>setSkills(skills.filter(x=>x!==s))} key={s} className="rounded-xl border bg-white px-3 py-2 text-sm">{s} ×</button>)}</div><div className="mt-5 flex gap-2"><input value={value} onChange={e=>setValue(e.target.value)} placeholder="Add a skill" className="flex-1 rounded-xl border p-3"/><Button onClick={()=>{if(value.trim()){setSkills([...skills,value.trim()]);setValue('')}}}><Plus size={16} className="mr-1 inline"/>Add</Button></div></Card>; }
function AddSkill() { const [added,setAdded]=useState(false); return <Card><h2 className="text-xl font-bold">Create a skill listing</h2><div className="mt-5 grid gap-4 md:grid-cols-2"><input placeholder="Skill name" className="rounded-xl border p-3"/><select className="rounded-xl border p-3"><option>Intermediate</option><option>Beginner</option><option>Advanced</option></select><select className="rounded-xl border p-3"><option>Technology</option><option>Design</option><option>Languages</option><option>Business</option></select><input placeholder="Hours available / week" className="rounded-xl border p-3"/><textarea placeholder="Describe what you can teach..." className="min-h-28 rounded-xl border p-3 md:col-span-2"/></div><div className="mt-5"><Button onClick={()=>setAdded(true)}>{added?'Skill added ✓':'Publish skill'}</Button></div></Card>; }
function Goals() { return <div className="grid gap-4 md:grid-cols-3">{[['Master React','8/10 sessions','2 weeks left'],['Build ML portfolio','3/6 projects','1 month left'],['Improve communication','5/8 practice calls','12 days left']].map(([a,b,c])=><Card key={a}><BookOpen size={20} className="text-indigo-600"/><h3 className="mt-3 font-bold">{a}</h3><p className="mt-1 text-sm text-slate-500">{b}</p><div className="mt-4 h-2 rounded-full bg-slate-100"><div className="h-2 w-2/3 rounded-full bg-indigo-500"/></div><p className="mt-2 text-xs text-slate-400">{c}</p></Card>)}</div>; }
function Teaching() { return <Card><h2 className="text-xl font-bold">Teaching portfolio</h2><div className="mt-5 grid gap-4 md:grid-cols-2">{[['React','Advanced','18 learners'],['Python','Intermediate','11 learners'],['Git & GitHub','Advanced','24 learners'],['NLP basics','Intermediate','7 learners']].map(([a,b,c])=><div key={a} className="rounded-xl border p-4"><div className="flex justify-between"><h3 className="font-semibold">{a}</h3><span className="text-xs text-indigo-600">{b}</span></div><p className="mt-2 text-sm text-slate-500">{c}</p><button type="button" className="mt-3 text-sm font-semibold text-indigo-600">Manage skill →</button></div>)}</div></Card>; }
function SearchScreen({advanced=false}:{advanced?:boolean}) { const [query,setQuery]=useState('React'); return <Card><div className="flex gap-2"><div className="relative flex-1"><Search size={18} className="absolute left-3 top-3.5 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} className="w-full rounded-xl border p-3 pl-10" placeholder="Search skills or people"/></div><Button><Search size={16} className="mr-1 inline"/>Search</Button></div>{advanced&&<div className="mt-4 grid gap-3 md:grid-cols-4"><select className="rounded-xl border p-3"><option>Any level</option><option>Beginner</option><option>Intermediate</option><option>Advanced</option></select><select className="rounded-xl border p-3"><option>Any category</option><option>Technology</option><option>Design</option></select><select className="rounded-xl border p-3"><option>Any availability</option><option>Evenings</option><option>Weekends</option></select><button type="button" className="rounded-xl border p-3 text-sm font-semibold"><SlidersHorizontal size={16} className="mr-2 inline"/>More filters</button></div>}<div className="mt-6 space-y-3">{people.map(([name,skill,match])=><div key={name} className="flex items-center justify-between rounded-xl border p-4"><div><p className="font-semibold">{name}</p><p className="text-sm text-slate-500">{skill} • {query}</p></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">{match}</span></div>)}</div></Card>; }
function Recommended() { return <div className="grid gap-4 md:grid-cols-3">{people.map(([n,s,m])=><Card key={n}><div className="flex items-center gap-3"><div className="flex h-12 w-12 items-center justify-center rounded-full bg-indigo-100 font-bold text-indigo-700">{n.split(' ').map(x=>x[0]).join('')}</div><div><h3 className="font-bold">{n}</h3><p className="text-xs text-slate-500">{s}</p></div></div><div className="mt-4 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700"><Sparkles size={15} className="mr-1 inline"/>{m} based on your goals</div><div className="mt-4 flex gap-2"><Button><UserPlus size={15} className="mr-1 inline"/>Connect</Button><Button secondary>View</Button></div></Card>)}</div>; }
function AIMatching() { return <Card><div className="rounded-2xl bg-indigo-50 p-6"><Sparkles className="text-indigo-600"/><h2 className="mt-3 text-2xl font-bold">AI match engine</h2><p className="mt-2 max-w-2xl text-sm text-slate-600">Matches are ranked using learning goals, teaching skills, availability and preferred learning mode.</p><div className="mt-5 grid gap-3 md:grid-cols-4">{[['Skills','40%'],['Goals','30%'],['Availability','20%'],['Preferences','10%']].map(([a,b])=><div className="rounded-xl bg-white p-4" key={a}><p className="text-xs text-slate-500">{a}</p><p className="mt-1 text-xl font-bold">{b}</p></div>)}</div></div><div className="mt-5 space-y-3">{people.map(([n,s,m])=><div key={n} className="flex items-center justify-between rounded-xl border p-4"><div><p className="font-semibold">{n}</p><p className="text-sm text-slate-500">{s}</p></div><Button>See match</Button></div>)}</div></Card>; }
function MatchDetails() { return <Card><div className="flex items-center justify-between"><div><p className="text-sm text-slate-500">Top recommendation</p><h2 className="text-2xl font-bold">Priya Sharma</h2></div><div className="rounded-2xl bg-emerald-50 p-4 text-center"><p className="text-3xl font-bold text-emerald-700">96%</p><p className="text-xs">compatibility</p></div></div><div className="mt-6 grid gap-4 md:grid-cols-3">{[['Skills overlap','98%'],['Goal alignment','94%'],['Schedule fit','92%']].map(([a,b])=><div className="rounded-xl bg-slate-50 p-4" key={a}><p className="text-sm text-slate-500">{a}</p><p className="mt-1 text-xl font-bold">{b}</p></div>)}</div><div className="mt-6 flex gap-3"><Link to="/screens/send-request"><Button>Send request</Button></Link><Button secondary>Save match</Button></div></Card>; }
function RequestForm() { const [sent,setSent]=useState(false); return <Card><h2 className="text-xl font-bold">Send a skill exchange request</h2><p className="mt-1 text-sm text-slate-500">Request a focused exchange with Priya Sharma.</p><div className="mt-5 grid gap-4"><input className="rounded-xl border p-3" defaultValue="Learn UI/UX fundamentals"/><select className="rounded-xl border p-3"><option>Teach React in return</option><option>Teach Python in return</option></select><textarea className="min-h-32 rounded-xl border p-3" defaultValue="I can offer two React sessions per week. I would like to learn practical UI/UX workflows."/><div><Button onClick={()=>setSent(true)}>{sent?'Request sent ✓':<><Send size={16} className="mr-1 inline"/>Send request</>}</Button></div></div></Card>; }
function Requests({sent=false}:{sent?:boolean}) { return <Card><div className="flex items-center justify-between"><h2 className="text-xl font-bold">{sent?'Sent requests':'Incoming requests'}</h2><span className="rounded-full bg-slate-100 px-3 py-1 text-xs">4 active</span></div><div className="mt-5 space-y-3">{people.map(([n,s],i)=><div key={n} className="flex flex-col gap-3 rounded-xl border p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold">{n}</p><p className="text-sm text-slate-500">{s}</p><p className="mt-1 text-xs text-slate-400">{i+1} day{i?'s':''} ago</p></div>{sent?<span className="rounded-full bg-amber-50 px-3 py-1 text-xs font-semibold text-amber-700">Pending</span>:<div className="flex gap-2"><Button>Accept</Button><Button secondary>Decline</Button></div>}</div>)}</div></Card>; }
function RequestDetails() { return <Card><div className="flex items-center gap-3"><div className="rounded-xl bg-indigo-50 p-3"><MessageCircle className="text-indigo-600"/></div><div><h2 className="text-xl font-bold">React ↔ UI/UX exchange</h2><p className="text-sm text-slate-500">Request from Priya Sharma • Pending</p></div></div><div className="mt-6 grid gap-4 md:grid-cols-2"><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-500">You teach</p><p className="mt-1 font-semibold">React, Git</p></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-500">You learn</p><p className="mt-1 font-semibold">UI/UX fundamentals</p></div></div><div className="mt-6 flex gap-3"><Button>Accept request</Button><Button secondary>Message member</Button></div></Card>; }
function ActiveExchange() { return <Card><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">ACTIVE</span><h2 className="mt-3 text-2xl font-bold">React ↔ UI/UX with Priya</h2><p className="text-sm text-slate-500">Week 2 of 4 • 6 sessions completed</p></div><Button>Open workspace</Button></div><div className="mt-6 h-3 rounded-full bg-slate-100"><div className="h-3 w-1/2 rounded-full bg-indigo-500"/></div><div className="mt-6 grid gap-4 md:grid-cols-3">{[['Next session','Today, 6:00 PM'],['Sessions done','6 / 12'],['Credits earned','30']].map(([a,b])=><div className="rounded-xl border p-4" key={a}><p className="text-xs text-slate-500">{a}</p><p className="mt-1 font-bold">{b}</p></div>)}</div></Card>; }
function History() { return <Card><h2 className="text-xl font-bold">Completed exchanges</h2><div className="mt-5 divide-y">{[['Python mentoring','Arjun Rao','Completed Aug 30'],['English conversation','Meera Nair','Completed Aug 21'],['Git fundamentals','Rahul Das','Completed Aug 10']].map(([a,b,c])=><div className="flex items-center justify-between py-4" key={a}><div><p className="font-semibold">{a}</p><p className="text-sm text-slate-500">with {b}</p></div><div className="text-right"><p className="text-sm font-medium">{c}</p><p className="text-xs text-emerald-600">5.0 ★</p></div></div>)}</div></Card>; }
function Rating() { const [rating,setRating]=useState(0); return <Card className="text-center"><Award className="mx-auto text-indigo-600" size={38}/><h2 className="mt-3 text-2xl font-bold">Rate your exchange</h2><p className="mt-1 text-sm text-slate-500">How was your learning experience with Priya?</p><div className="my-6 flex justify-center gap-2">{[1,2,3,4,5].map(i=><button key={i} onClick={()=>setRating(i)} type="button"><Star size={34} className={i<=rating?'fill-current text-amber-400':'text-slate-300'}/></button>)}</div><textarea placeholder="Share a short review (optional)" className="mx-auto min-h-28 w-full max-w-xl rounded-xl border p-3"/><div className="mt-4"><Button>{rating?`Submit ${rating}-star rating`:'Select a rating'}</Button></div></Card>; }
function Schedule() { const [done,setDone]=useState(false); return <Card><h2 className="text-xl font-bold">Schedule a session</h2><div className="mt-5 grid gap-4 md:grid-cols-3"><label className="text-sm font-medium">Date<input type="date" className="mt-2 w-full rounded-xl border p-3"/></label><label className="text-sm font-medium">Time<input type="time" className="mt-2 w-full rounded-xl border p-3"/></label><label className="text-sm font-medium">Duration<select className="mt-2 w-full rounded-xl border p-3"><option>60 minutes</option><option>90 minutes</option><option>120 minutes</option></select></label></div><label className="mt-4 block text-sm font-medium">Agenda<textarea className="mt-2 min-h-24 w-full rounded-xl border p-3" placeholder="What will you cover?"/></label><div className="mt-5"><Button onClick={()=>setDone(true)}>{done?'Session scheduled ✓':'Schedule session'}</Button></div></Card>; }
function CalendarScreen() { return <Card><div className="flex items-center justify-between"><div><h2 className="text-xl font-bold">September 2026</h2><p className="text-sm text-slate-500">Your exchange schedule</p></div><div className="flex gap-2"><Button secondary>‹</Button><Button secondary>›</Button></div></div><div className="mt-5 grid grid-cols-7 gap-2 text-center text-xs">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(d=><div key={d} className="p-2 font-semibold text-slate-400">{d}</div>)}{Array.from({length:30},(_,i)=><div key={i} className={`min-h-12 rounded-lg border p-2 ${[4,11,18,25].includes(i)?'border-indigo-300 bg-indigo-50':''}`}><span>{i+1}</span>{[4,11,18,25].includes(i)&&<div className="mt-1 text-[10px] font-semibold text-indigo-600">Exchange</div>}</div>)}</div></Card>; }
function Notifications() { return <Card><h2 className="text-xl font-bold">Notifications</h2><div className="mt-4 space-y-2">{[['New match','Priya is a 96% match for your learning goals.'],['Request accepted','Arjun accepted your Python exchange request.'],['Session reminder','Your React session starts in 2 hours.'],['Community reply','Meera replied to your NLP post.']].map(([a,b],i)=><div key={a} className="flex gap-3 rounded-xl p-4 hover:bg-slate-50"><div className="rounded-full bg-indigo-50 p-2"><Bell size={16} className="text-indigo-600"/></div><div className="flex-1"><p className="font-semibold">{a}</p><p className="text-sm text-slate-500">{b}</p></div><span className="text-xs text-slate-400">{i+1}h</span></div>)}</div></Card>; }
function NotificationSettings() { const [enabled,setEnabled]=useState({requests:true,messages:true,sessions:true,community:false}); return <Card><h2 className="text-xl font-bold">Notification preferences</h2><div className="mt-5 space-y-2">{Object.entries(enabled).map(([key,value])=><label key={key} className="flex items-center justify-between rounded-xl border p-4"><div><p className="font-semibold capitalize">{key}</p><p className="text-xs text-slate-500">Receive updates about {key}.</p></div><input type="checkbox" checked={value} onChange={()=>setEnabled({...enabled,[key]:!value})} className="h-5 w-5"/></label>)}</div></Card>; }
function ChatDetails() { const [message,setMessage]=useState(''); const [sent,setSent]=useState<string[]>([]); return <Card><div className="border-b pb-4"><h2 className="text-xl font-bold">Chat with Priya Sharma</h2><p className="text-sm text-emerald-600">Online • React ↔ UI/UX exchange</p></div><div className="min-h-72 space-y-3 py-5"><div className="max-w-md rounded-2xl bg-slate-100 p-3 text-sm"><p className="mb-1 text-[10px] opacity-70">Priya</p>Hi! Ready for today’s design review?</div><div className="ml-auto max-w-md rounded-2xl bg-indigo-600 p-3 text-sm text-white"><p className="mb-1 text-[10px] opacity-70">You</p>Yes, I prepared the React component flow.</div>{sent.map(x=><div key={x} className="ml-auto max-w-md rounded-2xl bg-indigo-600 p-3 text-sm text-white">{x}</div>)}</div><div className="flex gap-2"><input value={message} onChange={e=>setMessage(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&message.trim()){setSent([...sent,message.trim()]);setMessage('')}}} className="flex-1 rounded-xl border p-3" placeholder="Type a message..."/><Button onClick={()=>{if(message.trim()){setSent([...sent,message.trim()]);setMessage('')}}}><Send size={16}/></Button></div></Card>; }
function CreatePost() { const [posted,setPosted]=useState(false); return <Card><h2 className="text-xl font-bold">Create a community post</h2><div className="mt-5 grid gap-4"><input className="rounded-xl border p-3" placeholder="Post title"/><select className="rounded-xl border p-3"><option>Question</option><option>Learning tip</option><option>Project update</option><option>Resource</option></select><textarea className="min-h-40 rounded-xl border p-3" placeholder="Share something useful with the community..."/><Button onClick={()=>setPosted(true)}>{posted?'Published ✓':'Publish post'}</Button></div></Card>; }
function PostDetails() { return <Card><div className="flex gap-3"><div className="rounded-full bg-indigo-100 p-3 font-bold text-indigo-700">PS</div><div><p className="font-semibold">Priya Sharma</p><p className="text-xs text-slate-400">2 hours ago • NLP</p></div></div><h2 className="mt-5 text-2xl font-bold">What is the best way to evaluate an NLP project?</h2><p className="mt-3 leading-7 text-slate-600">I am comparing accuracy, F1 score and human evaluation for a small text classification project. What metrics do you normally use?</p><div className="mt-5 flex gap-4 text-sm text-slate-500"><span><Heart size={16} className="mr-1 inline"/>18</span><span>12 replies</span><span><Flag size={16} className="mr-1 inline"/>Report</span></div><div className="mt-6 border-t pt-5"><h3 className="font-semibold">Replies</h3><div className="mt-3 rounded-xl bg-slate-50 p-4"><p className="font-medium">Arjun Rao</p><p className="mt-1 text-sm text-slate-600">Use F1 when the classes are imbalanced, then add a small human review for qualitative errors.</p></div></div></Card>; }
function Groups() { return <div className="grid gap-4 md:grid-cols-3">{[['AI & Machine Learning','2.4k members','Active today'],['Frontend Builders','1.8k members','42 new posts'],['Career Switchers','980 members','Active this week']].map(([a,b,c])=><Card key={a}><Globe2 className="text-indigo-600"/><h3 className="mt-3 font-bold">{a}</h3><p className="mt-1 text-sm text-slate-500">{b}</p><div className="mt-3 rounded-lg bg-slate-50 p-2 text-xs">{c}</div><div className="mt-4"><Button>Join group</Button></div></Card>)}</div>; }
function GroupDetails() { return <Card><div className="rounded-2xl bg-slate-100 p-6"><Users className="text-indigo-600"/><h2 className="mt-3 text-2xl font-bold">Frontend Builders</h2><p className="mt-1 text-sm text-slate-500">A practical community for React, TypeScript and modern frontend development.</p><div className="mt-4 flex gap-3 text-sm"><span>1,842 members</span><span>•</span><span>42 online</span></div></div><div className="mt-5 grid gap-4 md:grid-cols-2"><div><h3 className="font-semibold">Pinned discussion</h3><p className="mt-2 rounded-xl border p-4 text-sm">Show your latest project and get feedback.</p></div><div><h3 className="font-semibold">Upcoming</h3><p className="mt-2 rounded-xl border p-4 text-sm">Community code review • Friday 7 PM</p></div></div></Card>; }
function Workshops() { return <div className="grid gap-4 md:grid-cols-3">{[['React in 90 Minutes','Priya Sharma','Today • 7 PM','24 seats'],['Build an ML Portfolio','Arjun Rao','Sep 18 • 6 PM','12 seats'],['Public Speaking Practice','Meera Nair','Sep 20 • 5 PM','8 seats']].map(([a,b,c,d])=><Card key={a}><div className="flex justify-between"><BookOpen className="text-indigo-600"/><span className="rounded-full bg-emerald-50 px-2 py-1 text-xs text-emerald-700">Open</span></div><h3 className="mt-4 font-bold">{a}</h3><p className="mt-1 text-sm text-slate-500">Host: {b}</p><p className="mt-3 text-sm">{c}</p><p className="mt-1 text-xs text-slate-400">{d}</p><div className="mt-4"><Button>View workshop</Button></div></Card>)}</div>; }
function CreateWorkshop() { const [created,setCreated]=useState(false); return <Card><h2 className="text-xl font-bold">Create a workshop</h2><div className="mt-5 grid gap-4 md:grid-cols-2"><input className="rounded-xl border p-3" placeholder="Workshop title"/><input className="rounded-xl border p-3" placeholder="Skill / topic"/><input type="date" className="rounded-xl border p-3"/><input type="time" className="rounded-xl border p-3"/><input className="rounded-xl border p-3" placeholder="Maximum participants"/><select className="rounded-xl border p-3"><option>Free • Skill credits</option><option>Premium members</option></select><textarea className="min-h-28 rounded-xl border p-3 md:col-span-2" placeholder="Workshop description"/></div><div className="mt-5"><Button onClick={()=>setCreated(true)}>{created?'Workshop created ✓':'Create workshop'}</Button></div></Card>; }
function WorkshopDetails() { const [joined,setJoined]=useState(false); return <Card><div className="flex flex-col gap-5 lg:flex-row lg:justify-between"><div><span className="rounded-full bg-indigo-50 px-3 py-1 text-xs font-bold text-indigo-700">WORKSHOP</span><h2 className="mt-4 text-3xl font-bold">React in 90 Minutes</h2><p className="mt-2 text-slate-500">Build a small responsive interface while learning reusable React patterns.</p></div><div className="rounded-2xl bg-slate-50 p-5 lg:w-64"><p className="text-sm text-slate-500">Starts</p><p className="font-bold">Today, 7:00 PM</p><p className="mt-3 text-sm text-slate-500">Seats</p><p className="font-bold">18 / 24</p><div className="mt-4"><Button onClick={()=>setJoined(true)}>{joined?'Joined ✓':'Join workshop'}</Button></div></div></div><div className="mt-6 grid gap-4 md:grid-cols-3">{[['Host','Priya Sharma'],['Duration','90 minutes'],['Format','Live online']].map(([a,b])=><div className="rounded-xl border p-4" key={a}><p className="text-xs text-slate-500">{a}</p><p className="mt-1 font-semibold">{b}</p></div>)}</div></Card>; }
function MyWorkshops() { return <Card><div className="flex items-center justify-between"><h2 className="text-xl font-bold">My workshops</h2><Link to="/screens/create-workshop"><Button><Plus size={16} className="mr-1 inline"/>Create</Button></Link></div><div className="mt-5 space-y-3">{[['React in 90 Minutes','Hosting','24 registered'],['NLP Project Clinic','Hosting','12 registered'],['ML Portfolio Review','Joined','1 session left']].map(([a,b,c])=><div className="flex items-center justify-between rounded-xl border p-4" key={a}><div><p className="font-semibold">{a}</p><p className="text-sm text-slate-500">{b} • {c}</p></div><ChevronRight size={18}/></div>)}</div></Card>; }
function Credits() { return <><Card><div className="flex items-center justify-between"><div><p className="text-sm text-slate-500">Available skill credits</p><p className="mt-1 text-4xl font-bold">180</p></div><div className="rounded-2xl bg-indigo-50 p-4"><CreditCard className="text-indigo-600"/></div></div><div className="mt-5 h-3 rounded-full bg-slate-100"><div className="h-3 w-3/4 rounded-full bg-indigo-500"/></div><p className="mt-2 text-xs text-slate-500">20 credits expire in 30 days.</p></Card><Card className="mt-4"><h2 className="font-bold">Recent credit activity</h2><div className="mt-3 divide-y">{[['Earned','Completed Python exchange','+30'],['Spent','Workshop registration','-20'],['Earned','Helped a new member','+15']].map(([a,b,c])=><div className="flex justify-between py-3" key={b}><div><p className="font-medium">{a}</p><p className="text-xs text-slate-500">{b}</p></div><span className={c.startsWith('+')?'text-emerald-600':'text-slate-600'}>{c}</span></div>)}</div></Card></>; }
function Premium() { return <Card><div className="rounded-3xl bg-slate-900 p-7 text-white"><Zap/><h2 className="mt-3 text-3xl font-bold">Premium Membership</h2><p className="mt-2 max-w-xl text-slate-300">Unlock priority AI matching, advanced discovery, featured skills and enhanced exchange insights.</p><div className="mt-6 grid gap-3 md:grid-cols-3">{['Priority AI matching','Featured skill listings','Advanced analytics'].map(x=><div className="rounded-xl bg-white/10 p-4" key={x}><Check size={16} className="mb-2"/>{x}</div>)}</div><div className="mt-6 flex gap-3"><Button>Upgrade membership</Button><Button secondary>Compare plans</Button></div></div></Card>; }
function Verification() { const [submitted,setSubmitted]=useState(false); return <Card><div className="flex items-center gap-3"><div className="rounded-xl bg-emerald-50 p-3"><ShieldCheck className="text-emerald-600"/></div><div><h2 className="text-xl font-bold">Verification Center</h2><p className="text-sm text-slate-500">Build trust with the community.</p></div></div><div className="mt-6 space-y-3">{[['Email verification','Completed',true],['Phone verification','Completed',true],['Identity verification','Not submitted',false]].map(([a,b,c])=><div className="flex items-center justify-between rounded-xl border p-4" key={String(a)}><div><p className="font-semibold">{a}</p><p className="text-sm text-slate-500">{b}</p></div>{c?<CheckCircle2 className="text-emerald-500"/>:<Button onClick={()=>setSubmitted(true)}>{submitted?'Submitted':'Start'}</Button>}</div>)}</div></Card>; }
function Support() { return <Card><h2 className="text-2xl font-bold">How can we help?</h2><p className="mt-1 text-sm text-slate-500">Search common issues or contact support.</p><div className="mt-5 flex gap-2"><input className="flex-1 rounded-xl border p-3" placeholder="Search help articles"/><Button><Search size={16}/></Button></div><div className="mt-6 grid gap-3 md:grid-cols-3">{[['Account','Login, profile and verification'],['Exchanges','Requests, scheduling and ratings'],['Community','Posts, groups and moderation']].map(([a,b])=><div className="rounded-xl border p-4" key={a}><HelpCircle className="text-indigo-600"/><h3 className="mt-3 font-semibold">{a}</h3><p className="mt-1 text-sm text-slate-500">{b}</p></div>)}</div></Card>; }
function FAQ() { const [open,setOpen]=useState<number|null>(null); const qs=['How does skill exchange work?','Do I need to pay to use SkillBarter?','How are AI matches calculated?','How do skill credits work?']; return <Card><h2 className="text-xl font-bold">Frequently asked questions</h2><div className="mt-5 space-y-2">{qs.map((q,i)=><div className="rounded-xl border" key={q}><button type="button" onClick={()=>setOpen(open===i?null:i)} className="flex w-full items-center justify-between p-4 text-left font-semibold">{q}<ChevronRight size={18} className={open===i?'rotate-90':''}/></button>{open===i&&<p className="border-t px-4 py-4 text-sm leading-6 text-slate-600">SkillBarter helps members exchange practical skills without requiring cash. You discover a compatible partner, agree on what each person will teach, schedule sessions and rate the completed exchange.</p>}</div>)}</div></Card>; }
function Privacy() { const [settings,setSettings]=useState({profile:true,activity:false,discoverable:true}); return <Card><div className="flex items-center gap-3"><Lock className="text-indigo-600"/><div><h2 className="text-xl font-bold">Privacy & Security</h2><p className="text-sm text-slate-500">Control what other members can discover.</p></div></div><div className="mt-6 space-y-3">{Object.entries(settings).map(([k,v])=><label className="flex items-center justify-between rounded-xl border p-4" key={k}><div><p className="font-semibold capitalize">{k} visibility</p><p className="text-xs text-slate-500">Manage how this information is shared.</p></div><input type="checkbox" checked={v} onChange={()=>setSettings({...settings,[k]:!v})} className="h-5 w-5"/></label>)}</div><div className="mt-5 flex gap-3"><Button>Save privacy settings</Button><Button secondary>Review sessions</Button></div></Card>; }
function AccountSettings() { const [saved,setSaved]=useState(false); return <Card><h2 className="text-xl font-bold">Account settings</h2><div className="mt-5 grid gap-4 md:grid-cols-2"><label className="text-sm font-medium">Language<select className="mt-2 w-full rounded-xl border p-3"><option>English</option><option>Telugu</option><option>Hindi</option></select></label><label className="text-sm font-medium">Timezone<select className="mt-2 w-full rounded-xl border p-3"><option>Asia/Kolkata</option><option>UTC</option></select></label><label className="text-sm font-medium">Theme<select className="mt-2 w-full rounded-xl border p-3"><option>System</option><option>Light</option><option>Dark</option></select></label><label className="text-sm font-medium">Profile visibility<select className="mt-2 w-full rounded-xl border p-3"><option>Community</option><option>Connections only</option></select></label></div><div className="mt-5"><Button onClick={()=>setSaved(true)}>{saved?'Settings saved ✓':'Save settings'}</Button></div></Card>; }
function Activity() { return <Card><div className="flex items-center justify-between"><h2 className="text-xl font-bold">Activity history</h2><button type="button" className="text-sm text-indigo-600">Clear filters</button></div><div className="mt-5 space-y-4">{[['Today, 6:14 PM','Accepted an exchange request','Exchanges'],['Today, 4:02 PM','Joined Frontend Builders','Community'],['Yesterday, 8:30 PM','Completed React workshop','Learning'],['Sep 10, 7:10 PM','Updated teaching skills','Profile']].map(([time,a,b])=><div className="flex gap-4" key={time}><div className="mt-1 h-3 w-3 rounded-full bg-indigo-500"/><div className="flex-1 border-b pb-4"><p className="font-medium">{a}</p><p className="mt-1 text-xs text-slate-400">{time} • {b}</p></div></div>)}</div></Card>; }

function Content({id}:{id:string}) { switch(id) {
  case 'dashboard': return <Dashboard/>; case 'edit-profile': return <EditProfile/>; case 'public-profile': return <PublicProfile/>; case 'skills': return <Skills/>; case 'add-skill': return <AddSkill/>; case 'learning-goals': return <Goals/>; case 'teaching-skills': return <Teaching/>; case 'search': return <SearchScreen/>; case 'advanced-search': return <SearchScreen advanced/>; case 'recommended': return <Recommended/>; case 'ai-matching': return <AIMatching/>; case 'match-details': return <MatchDetails/>; case 'send-request': return <RequestForm/>; case 'incoming-requests': return <Requests/>; case 'sent-requests': return <Requests sent/>; case 'request-details': return <RequestDetails/>; case 'active-exchange': return <ActiveExchange/>; case 'exchange-history': return <History/>; case 'exchange-rating': return <Rating/>; case 'schedule': return <Schedule/>; case 'calendar': return <CalendarScreen/>; case 'notifications': return <Notifications/>; case 'notification-settings': return <NotificationSettings/>; case 'chat-details': return <ChatDetails/>; case 'create-post': return <CreatePost/>; case 'post-details': return <PostDetails/>; case 'groups': return <Groups/>; case 'group-details': return <GroupDetails/>; case 'workshops': return <Workshops/>; case 'create-workshop': return <CreateWorkshop/>; case 'workshop-details': return <WorkshopDetails/>; case 'my-workshops': return <MyWorkshops/>; case 'credits': return <Credits/>; case 'premium': return <Premium/>; case 'verification': return <Verification/>; case 'support': return <Support/>; case 'faq': return <FAQ/>; case 'privacy': return <Privacy/>; case 'account-settings': return <AccountSettings/>; case 'activity': return <Activity/>; default: return <Dashboard/>;
} }

export function AdditionalScreensIndex() { const [query,setQuery]=useState(''); const filtered=useMemo(()=>screens.filter(([,title,desc])=>`${title} ${desc}`.toLowerCase().includes(query.toLowerCase())),[query]); return <div className="min-h-screen bg-slate-50 px-4 py-8"><div className="mx-auto max-w-6xl"><div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="text-sm font-semibold text-indigo-600">SkillBarter • Product Workspace</p><h1 className="mt-2 text-3xl font-bold text-slate-900">40 functional product screens</h1><p className="mt-2 max-w-2xl text-slate-600">Each screen now has its own workflow, controls and product-specific content.</p></div><div className="relative w-full md:w-80"><Search size={17} className="absolute left-3 top-3.5 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find a screen..." className="w-full rounded-xl border bg-white p-3 pl-10"/></div></div><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{filtered.map(([id,title,description,Icon],i)=><Link key={id} to={`/screens/${id}`} className="group rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-1 hover:shadow-md"><div className="flex items-center justify-between"><div className="rounded-xl bg-indigo-50 p-3 text-indigo-600"><Icon size={21}/></div><span className="text-xs font-semibold text-slate-400">{String(i+1).padStart(2,'0')}</span></div><h2 className="mt-4 font-semibold text-slate-900">{title}</h2><p className="mt-1 text-sm text-slate-500">{description}</p><p className="mt-4 text-sm font-semibold text-indigo-600">Open workflow <ArrowRight size={15} className="ml-1 inline transition group-hover:translate-x-1"/></p></Link>)}</div></div></div>; }

export function AdditionalScreen() { const {id='dashboard'}=useParams(); const entry=screens.find(([key])=>key===id)||screens[0]; const [key,title,description,Icon]=entry; const index=screens.findIndex(([k])=>k===key)+1; const previous=screens[index-2]; const next=screens[index]; return <div className="min-h-screen bg-slate-50 px-4 py-8"><div className="mx-auto max-w-6xl"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><Link to="/screens" className="inline-flex items-center gap-2 text-sm font-medium text-slate-600 hover:text-indigo-600"><ArrowLeft size={16}/> All product screens</Link><span className="rounded-full bg-indigo-50 px-3 py-1 text-xs font-bold text-indigo-700">Screen {index} of 40</span></div><div className="mb-6 flex items-start gap-4"><div className="rounded-2xl bg-indigo-50 p-4 text-indigo-600"><Icon size={28}/></div><div><h1 className="text-3xl font-bold text-slate-900">{title}</h1><p className="mt-1 text-slate-600">{description}</p></div></div><Content id={key}/><div className="mt-6 flex items-center justify-between"><div>{previous?<Link to={`/screens/${previous[0]}`} className="inline-flex items-center gap-2 rounded-xl border bg-white px-4 py-2.5 text-sm font-semibold text-slate-700"><ArrowLeft size={16}/> Previous</Link>:<span/>}</div><div>{next?<Link to={`/screens/${next[0]}`} className="inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white">Next <ArrowRight size={16}/></Link>:<Link to="/screens" className="rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white">Finish</Link>}</div></div></div></div>; }

export const additionalScreenCount = screens.length;
